### ISSUE TITLE
How to configure Flex Queries on IBKR?

### ISSUE THREAD

**Issue by stelewis** [OSadovy/uabean#1]
Hi Lex, thanks so much for sharing your importers, this is great. I'm trying to get started with your IBKR importer, but I'm not sure how to set up the Flex Query report on IBKR?

I've started by going to IBKR Performance and Reports > Flex Queries > Activity Flex Query and adding a new report. I saw elsewhere in the Google Groups that Martin uses the "Statement of Funds," section, but even within that there are a number of "Options" to select from (e.g., Currency Breakout, Include Starting and Ending Balances, etc.).

Is there a correct configuration for the Flex Query that I should be using here? I'm still quite new to beancount and beangulp, so please excuse my ignorance and feel free to direct me elsewhere if this is already documented! Thanks.

**Comment by OSadovy** [comment]
@stelewis  sorry for late repply, my github notifications seem to be not getting through.
Basically, there is a description of what sections to select & what options to add in the module docstring, at the top of the importer file: https://github.com/OSadovy/uabean/blob/master/src/uabean/importers/ibkr.py

for every section that is needed, I choose all the available fields. The unused fields are just ignored.

**Comment by OSadovy** [comment]
Closing this due to no additional comments from the author.
